name: Upload build to App Center

on: 
  push:
    branches:
      - stable

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: "18"
    - name: build release
      run: ./gradlew assembleRelease
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: tenshAMD/AndroidJetpackComposeDemo
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: Testers-Alpha
        file: app/build/outputs/apk/release/app-release-unsigned.apk
        notifyTesters: true
        debug: false
