name: Upload build to App Center

on: 
  push:
    branches:
      - stable
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: "18"
    - name: build release
      run: ./gradlew assembleDebug
    - name: Get message from latest commit
      id: get-latest-commit-message
      run: |
        echo "::set-output name=LATEST_COMMIT_MESSAGE::$(git log -1 --pretty=%B)"
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: tenshiAMD/AndroidJetpackComposeDemo
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: ${{secrets.APP_CENTER_GROUPS}}
        file: app/build/outputs/apk/debug/app-debug.apk
        notifyTesters: true
        debug: true
        releaseNotes: "${{ steps.get-latest-commit-message.outputs.LATEST_COMMIT_MESSAGE }}"
